<?php
namespace venveo\hubspottoolbox\features;

use venveo\hubspottoolbox\HubSpotToolbox;

class EcommerceFeature extends HubSpotFeature {

    public $storeId = '';

    public static function getName(): string
    {
        return 'E-Commerce';
    }

    public static function getHandle(): string
    {
        return 'ecommerce';
    }

    public function getSettingsHtml()
    {
        $stores = HubSpotToolbox::$plugin->ecomm->getStores();
        return \Craft::$app->getView()->renderTemplate('hubspot-toolbox/_features/ecommerce/_settings', [
            'feature' => $this,
            'stores' => $stores
        ]);
    }

    public function beforeSave(bool $isNew): bool
    {
        return parent::beforeSave($isNew); // TODO: Change the autogenerated stub
    }

    public function defineRules(): array
    {
        $rules = parent::defineRules();
        $rules[] = [['storeId'], 'required'];
        return $rules;
    }
}